<a href="https://colab.research.google.com/github/Siddhu290/Machine_Learning/blob/main/DL_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This cell imports the core PyTorch library, which is essential for building and training neural networks.

In [ ]:
import torch

This cell imports the `nn` module from PyTorch, which provides a rich set of layers and modules for creating neural network architectures.

In [ ]:
from torch import nn

Here, we import the `functional` module (aliased as `F`) from PyTorch. This module contains a wide range of functions, including activation functions, loss functions, and other operations that don't have learnable parameters but are often used in neural networks.

In [ ]:
import torch.nn.functional as F


This cell imports the `optim` module from PyTorch, which provides various optimization algorithms like Stochastic Gradient Descent (SGD), Adam, etc., used to update model parameters during training.

In [ ]:
import torch.optim as optim

We import `TensorDataset` and `DataLoader` from `torch.utils.data`. `TensorDataset` wraps tensors as a dataset, and `DataLoader` provides an iterator over the dataset, allowing us to process data in mini-batches for training.

In [ ]:
from torch.utils.data import TensorDataset, DataLoader

This cell first installs the `torchmetrics` library using `pip`, which provides a collection of common machine learning metrics implemented in PyTorch. After installation, it imports the library.

In [ ]:
!pip install torchmetrics
import torchmetrics

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.4/983.4 kB 17.2 MB/s eta 0:00:00


This cell creates a simple 1D PyTorch tensor named `tnsr` with integer values.

In [ ]:
tnsr = torch.tensor([1,3,6,10])

This cell checks and displays the data type of the `tnsr` tensor.

In [ ]:
tnsr.dtype

torch.int64

This cell checks and displays the shape (dimensions) of the `tnsr` tensor.

In [ ]:
tnsr.shape

torch.Size([4])

This cell checks and displays the device where the `tnsr` tensor is currently stored (e.g., 'cpu' or 'cuda' for GPU).

In [ ]:
tnsr.device

device(type='cpu')

This cell creates a 2x3 PyTorch tensor named `tnsr_zrs` and initializes all its elements to zero.

In [ ]:
tnsr_zrs = torch.zeros(2,3)

This cell simply displays the `tnsr_zrs` tensor created in the previous step.

In [ ]:
tnsr_zrs

tensor([[0., 0., 0.],
        [0., 0., 0.]])

This cell creates a 3x4 PyTorch tensor named `tnsr_rndm` and initializes its elements with random floating-point numbers sampled from a uniform distribution between 0 and 1. It then displays the tensor.

In [ ]:
tnsr_rndm = torch.rand(size=(3,4))
tnsr_rndm

tensor([[0.3469, 0.4450, 0.7861, 0.2195],
        [0.0617, 0.0526, 0.1267, 0.4430],
        [0.9578, 0.9343, 0.7583, 0.4981]])

This cell loads the well-known Iris dataset from `sklearn.datasets`, converts it into a pandas DataFrame, adds the 'target' column, and then displays the first 5 rows of the DataFrame. This is a common step for initial data inspection.

In [ ]:
from sklearn.datasets import load_iris
import pandas as pd
# Load the Iris dataset
iris = load_iris()

# Create a DataFrame from the dataset
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['target'] = iris.target

# Display the first 5 rows of the Iris dataset
display(iris_df.head())

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0


Here, we define the feature columns for our model and extract them from the `iris_df` DataFrame, converting them into a NumPy array `x`. These will be the input features for our neural network.

In [ ]:
# Define feature columns from the Iris dataset
feature_columns = ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
x = iris_df[feature_columns].values

This cell extracts the 'target' column from the `iris_df` DataFrame, converting it into a NumPy array `y`. These are the ground-truth labels our model will try to predict.

In [ ]:
y = iris_df['target'].values

This cell creates a `TensorDataset` by pairing the input features `x` and target labels `y`. Both are converted to PyTorch tensors and cast to `float` data type, which is typically required for neural network inputs.

In [ ]:
dataset = TensorDataset(torch.tensor(x).float(), torch.tensor(y).float())

This cell displays the `TensorDataset` object, showing its type and memory location.

In [ ]:
dataset

This cell defines a batch size `n` (which is 32) and then creates a `DataLoader`. The `DataLoader` shuffles the dataset and provides an iterable that yields data in batches, which is crucial for efficient training of neural networks.

In [ ]:
n = 32 # Define batch size
dataloader = DataLoader(dataset, batch_size=n, shuffle=True)

This cell demonstrates the usage of `F.one_hot` to convert integer class labels `[0, 1, 2]` into their corresponding one-hot encoded vectors. This is often necessary for certain loss functions in multi-class classification.

In [ ]:
F.one_hot(torch.tensor([0,1,2]),num_classes=3)

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

This cell initializes a linear layer (`nn.Linear`) with 2 input features and 4 output features. It then displays the linear layer object, showing its configuration.

In [ ]:
m=2
n=4
lnr = nn.Linear(m,n)
lnr

Linear(in_features=2, out_features=4, bias=True)

This cell displays the weight matrix (`lnr.weight`) of the linear layer initialized previously. These are the learnable parameters that connect the inputs to the outputs of this layer.

In [ ]:
lnr.weight

Parameter containing:
tensor([[-0.1389, -0.1601],
        [ 0.1914, -0.6695],
        [ 0.5335,  0.0279],
        [ 0.2166, -0.2811]], requires_grad=True)

This cell displays the bias vector (`lnr.bias`) of the linear layer. The bias is another set of learnable parameters added to the output of the linear transformation.

In [ ]:
lnr.bias

Parameter containing:
tensor([-0.4925,  0.4133,  0.2147,  0.1619], requires_grad=True)

This cell initializes a `Sigmoid` activation function, which squashes input values between 0 and 1. It's often used in the output layer for binary classification or in hidden layers for non-linearity.

In [ ]:
a=nn.Sigmoid()

This cell initializes a `Softmax` activation function. `Softmax` is typically used in the output layer of a multi-class classification network to convert raw scores (logits) into probability distributions over the classes.

In [ ]:
from torch._prims_common import Dim
nn.Softmax(dim=-1)

Softmax(dim=-1)

This cell initializes a `ReLU` (Rectified Linear Unit) activation function, which outputs the input directly if it's positive, otherwise it outputs zero. It's a very common activation function in hidden layers.

In [ ]:
nn.ReLU()

ReLU()

This cell initializes a `LeakyReLU` activation function with a negative slope of 0.05. Unlike ReLU, LeakyReLU allows a small, non-zero gradient when the input is negative, which can help prevent 'dying ReLUs'.

In [ ]:
nn.LeakyReLU(negative_slope=0.05)

LeakyReLU(negative_slope=0.05)

This cell initializes a `Dropout` layer with a dropout probability of 0.5. Dropout is a regularization technique that randomly sets a fraction of input units to zero at each update during training, which helps prevent overfitting.

In [ ]:
nn.Dropout(p=0.5)

Dropout(p=0.5, inplace=False)

This cell defines the full neural network model using `nn.Sequential`. It consists of two hidden layers with ReLU activations, and an output layer with a Softmax activation for multi-class classification. The input features, hidden layer sizes, and number of output classes are determined dynamically from the data.

In [ ]:
from torch.nn.modules.activation import Softmax

# Define the input, hidden, and output sizes for the model
n_feature = x.shape[1]  # Number of input features (from 'x')
n_classes = len(torch.unique(torch.tensor(y))) # Number of output classes (from 'y')
i = 10  # Number of neurons in the first hidden layer
j = 8   # Number of neurons in the second hidden layer

model = nn.Sequential(nn.Linear(n_feature, i),
                       nn.ReLU(),
                       nn.Linear(i, j),
                       nn.ReLU(),
                       nn.Linear(j, n_classes),
                       nn.Softmax(dim=-1))

This cell performs a forward pass through the `model` with `sample_input` (which is our `x` features converted to a tensor). The output `prediction` represents the model's predicted probabilities for each class for every input sample.

In [ ]:
sample_input = torch.tensor(x).float()
prediction = model(sample_input)
print(prediction)

tensor([[0.2851, 0.4137, 0.3012],
        [0.2966, 0.4105, 0.2928],
        [0.2950, 0.4079, 0.2971],
        [0.2946, 0.4083, 0.2971],
        [0.2836, 0.4128, 0.3037],
        [0.2704, 0.4183, 0.3113],
        [0.2894, 0.4072, 0.3034],
        [0.2863, 0.4132, 0.3005],
        [0.3014, 0.4048, 0.2938],
        [0.2934, 0.4123, 0.2943],
        [0.2780, 0.4181, 0.3038],
        [0.2858, 0.4118, 0.3023],
        [0.2975, 0.4102, 0.2923],
        [0.3047, 0.4022, 0.2931],
        [0.2742, 0.4206, 0.3052],
        [0.2618, 0.4205, 0.3177],
        [0.2761, 0.4152, 0.3087],
        [0.2848, 0.4129, 0.3023],
        [0.2713, 0.4223, 0.3064],
        [0.2772, 0.4141, 0.3087],
        [0.2813, 0.4193, 0.2995],
        [0.2788, 0.4132, 0.3080],
        [0.2915, 0.4051, 0.3033],
        [0.2838, 0.4134, 0.3028],
        [0.2814, 0.4142, 0.3043],
        [0.2931, 0.4133, 0.2936],
        [0.2840, 0.4125, 0.3035],
        [0.2832, 0.4156, 0.3012],
        [0.2867, 0.4146, 0.2987],
        [0.290

This cell converts the NumPy array `y` (target labels) into a PyTorch tensor and casts it to `long` data type. Integer labels are often required by loss functions like `CrossEntropyLoss`.

In [ ]:
actual = torch.tensor(y).long()

Here, the `actual` target labels are one-hot encoded using `F.one_hot` to match the dimensionality of the `prediction` tensor. Then, the Mean Squared Error (MSE) loss is calculated between the `prediction` and `one_hot_actual`.

In [ ]:
one_hot_actual = F.one_hot(actual, num_classes=n_classes).float()
mse_loss = nn.MSELoss()(prediction, one_hot_actual)

This cell calculates the Smooth L1 Loss between the model's `prediction` and the `one_hot_actual` target labels. Smooth L1 Loss is less sensitive to outliers than MSE Loss.

In [ ]:
l1_loss = nn.SmoothL1Loss()(prediction, one_hot_actual)

This cell displays the computed Mean Squared Error (MSE) loss.

In [ ]:
mse_loss

tensor(0.2205, grad_fn=<MseLossBackward0>)

This cell displays the computed Smooth L1 Loss.

In [ ]:
l1_loss

tensor(0.1102, grad_fn=<SmoothL1LossBackward0>)

This cell displays the `actual` target labels tensor (integer class IDs).

In [ ]:
actual

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2])

This cell displays the `one_hot_actual` tensor, which represents the target labels in a one-hot encoded format.

In [ ]:
one_hot_actual

tensor([[1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1

This cell calculates the Binary Cross-Entropy (BCE) loss between the model's `prediction` (probabilities) and the `one_hot_actual` target labels. BCE is typically used for binary classification, or multi-label classification where each label is independent.

In [ ]:
bc3_loss = nn.BCELoss()(prediction, one_hot_actual)

This cell displays the computed Binary Cross-Entropy (BCE) loss.

In [ ]:
bc3_loss

tensor(0.6311, grad_fn=<BinaryCrossEntropyBackward0>)

This cell calculates the Cross-Entropy (CE) loss between the model's `prediction` and the `one_hot_actual` target labels. Note that `nn.CrossEntropyLoss` typically expects raw logits (scores before Softmax) and integer labels, so using it with one-hot encoded probabilities might not be the standard use case here.

In [ ]:
ce_loss = nn.CrossEntropyLoss()(prediction, one_hot_actual)

This cell displays the computed Cross-Entropy (CE) loss.

In [ ]:
ce_loss

tensor(1.0913, grad_fn=<DivBackward1>)

This cell assigns the `mse_loss` to a variable named `loss` and then calls `loss.backward()`. This crucial step computes the gradients of the `loss` with respect to all learnable parameters in the model.

In [ ]:
loss = mse_loss
loss.backward()

This cell displays the value of the `loss` tensor. Note that `loss.backward()` only computes gradients; it does not change the `loss` value itself.

In [ ]:
loss

tensor(0.2205, grad_fn=<MseLossBackward0>)

This cell initializes an `SGD` (Stochastic Gradient Descent) optimizer. It takes the model's learnable parameters (`model.parameters()`) and configures the learning rate (`lr=0.01`) and momentum (`momentum=0.95`), which are hyperparameters for the optimization process.

In [ ]:
from torch.optim import optimizer
optimizer = optim.SGD(model.parameters(), lr=0.01, momentum=0.95)

This cell displays the initialized `SGD` optimizer object, showing its configuration and the parameter groups it manages.

In [ ]:
optimizer

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    fused: None
    lr: 0.01
    maximize: False
    momentum: 0.95
    nesterov: False
    weight_decay: 0
)

This cell calls `optimizer.step()`. This function performs a single optimization step, using the gradients computed by `loss.backward()` to update the model's parameters according to the chosen optimization algorithm (SGD in this case).

In [ ]:
optimizer.step()

This cell sets the model to training mode (`model.train()`). This is important because certain layers, like Dropout and BatchNorm, behave differently during training and evaluation.

In [ ]:
model.train()

Sequential(
  (0): Linear(in_features=4, out_features=10, bias=True)
  (1): ReLU()
  (2): Linear(in_features=10, out_features=8, bias=True)
  (3): ReLU()
  (4): Linear(in_features=8, out_features=3, bias=True)
  (5): Softmax(dim=-1)
)

This cell re-defines the loss criterion as `nn.MSELoss()`. This loss function will be used to quantify the difference between the model's predictions and the true labels during training.

In [ ]:
loss_criterion = nn.MSELoss()

This cell re-initializes the `SGD` optimizer for the model's parameters with the same learning rate and momentum as before. This step is necessary if the model parameters were updated or reset.

In [ ]:
optimizer = optim.SGD(model.parameters(), lr=0.01, momentum=0.95)

This cell displays the re-initialized `SGD` optimizer object, confirming its current configuration.

In [ ]:
optimizer

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    fused: None
    lr: 0.01
    maximize: False
    momentum: 0.95
    nesterov: False
    weight_decay: 0
)

This cell contains the core training loop for a single epoch. It iterates through the `dataloader` to get batches of features and targets, performs a forward pass, calculates the loss, performs backpropagation (`loss.backward()`), and updates the model's parameters (`optimizer.step()`). `optimizer.zero_grad()` is called at the beginning of each batch to clear previous gradients.

In [ ]:
for data in dataloader:
  optimizer.zero_grad()
  features, target = data
  predictions = model(features)
  one_hot_target = F.one_hot(target.long(), num_classes=n_classes).float() # One-hot encode the target
  loss = loss_criterion(predictions, one_hot_target)
  loss.backward()
  optimizer.step()

This cell sets the model to evaluation mode (`model.eval()`). In this mode, layers like Dropout are disabled, and BatchNorm layers use their accumulated running statistics instead of batch statistics, ensuring consistent behavior during inference.

In [ ]:
model.eval()

Sequential(
  (0): Linear(in_features=4, out_features=10, bias=True)
  (1): ReLU()
  (2): Linear(in_features=10, out_features=8, bias=True)
  (3): ReLU()
  (4): Linear(in_features=8, out_features=3, bias=True)
  (5): Softmax(dim=-1)
)

This cell initializes an `Accuracy` metric from `torchmetrics`. It's configured for multiclass classification (`task='multiclass'`) and specifies the number of classes (`num_classes=3`). This metric will be used to evaluate the model's performance.

In [ ]:
metric = torchmetrics.Accuracy(task='multiclass', num_classes=3)

This cell iterates through the `dataloader` to evaluate the model's accuracy. For each batch, it gets predictions from the model and updates the `metric` with the predictions and the true target labels (converted to `long`). Finally, `metric.compute()` calculates the overall accuracy.

In [ ]:
for i , data in enumerate(dataloader, 0):
  features, target = data
  predictions = model(features)
  # For accuracy, we need the original target labels (not one-hot encoded)
  # and the predicted class from the model output
  accuracy = metric(predictions, target.long())

accuracy = metric.compute()
accuracy

tensor(0.3333)

This cell displays the final computed accuracy value from the `torchmetrics` object.

In [ ]:
accuracy

tensor(0.3333)

This cell resets the internal state of the `torchmetrics` accuracy metric. This is important if you want to calculate accuracy for a new set of predictions without being influenced by previous computations.

In [ ]:
metric.reset()

This cell saves the entire `model` object to a file named 'model.pth'. This allows you to persist the trained model and reload it later without having to retrain it.

In [ ]:
torch.save(model, 'model.pth')

This cell loads the saved model from 'model.pth' into a new variable `new_layer`. The `weights_only=False` argument is crucial here to ensure that the entire model architecture, along with its learned parameters, is loaded, resolving the `UnpicklingError` encountered previously.

In [ ]:
new_layer = torch.load('model.pth', weights_only=False)

This cell iterates through the named parameters of the `model` and sets `requires_grad` to `False` for the weights of the first linear layer (`'0.weight'`). This effectively 'freezes' these parameters, preventing them from being updated during subsequent training.

In [ ]:
for name, param in model.named_parameters():
  if name == '0.weight':
    param.requires_grad = False