<a href="https://colab.research.google.com/github/Siddhu290/Machine_Learning/blob/main/phase1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# 🔹 MODULE 1 — PRACTICAL TASK SYSTEM

We’ll build:

# 🏢 “E-Commerce Sales Analytics Pipeline”

You will:

* Clean messy data
* Engineer features
* Store into PostgreSQL
* Write optimized SQL queries
* Generate analytical insights

---

# 📦 DATASET STRUCTURE (You Create It)

Create 3 CSV files manually (small synthetic dataset ~200–500 rows):

---

## 1️⃣ customers.csv

Columns:

* customer_id
* name
* age
* city
* signup_date

Add:

* Some missing ages
* Some duplicate customers
* Random city names

---

## 2️⃣ orders.csv

Columns:

* order_id
* customer_id
* product_id
* quantity
* order_date
* price

Add:

* Some missing prices
* Some wrong quantities (0 or negative)
* Duplicate order rows

---

## 3️⃣ products.csv

Columns:

* product_id
* product_name
* category
* cost_price

Add:

* Different categories
* Some inconsistent category names (e.g., "Electronics" vs "electronics")

---

Now comes the real learning.

---

# 🔥 TASK 1 — NUMPY (Foundational Understanding)

### 🎯 Goal: Master ndarray & vectorization

## Tasks:

1. Load orders.csv numeric columns into NumPy array
2. Compute:

   * Total revenue per order using vectorized multiplication
   * Mean, median, std deviation of prices
3. Remove negative quantities using boolean masking
4. Normalize prices using formula:

[
x_{norm} = \frac{x - mean}{std}
]

5. Compute correlation between quantity and price

---

### Topics You Will Learn:

* ndarray creation
* Indexing & slicing
* Boolean masking
* Broadcasting
* Vectorized operations
* np.mean(), np.std(), np.corrcoef()

---

# 🔥 TASK 2 — PANDAS (Real Data Cleaning)

Now use Pandas for full pipeline.

---

## Step 1 — Load & Inspect

* df.head()
* df.info()
* df.describe()
* Check null values
* Detect duplicates

---

## Step 2 — Clean Data

You must:

✅ Remove duplicate rows
✅ Fill missing ages using median
✅ Fix category name inconsistencies
✅ Remove negative quantity rows
✅ Handle missing prices properly

---

## Step 3 — Feature Engineering

Create new columns:

* total_amount = quantity * price
* customer_age_group (18–25, 26–40, etc.)
* order_month
* is_repeat_customer (if customer has >1 order)

---

## Step 4 — Groupby Analytics

Calculate:

* Revenue per city
* Revenue per category
* Top 5 customers by revenue
* Monthly revenue trend

---

### Topics You Will Learn:

* groupby()
* agg()
* apply()
* merge()
* fillna()
* drop_duplicates()
* value_counts()
* feature engineering logic

---

# 🔥 TASK 3 — MERGING DATASETS

Now merge:

orders + customers + products

Create a single analytics dataframe.

Questions to answer:

1. Which city generates highest revenue?
2. Which category has highest profit?
3. What is average order value per age group?
4. Which month has peak sales?

---

Topics you’ll master:

* pd.merge()
* left join vs inner join
* multi-table merging
* relational thinking

---

# 🔥 TASK 4 — PostgreSQL (Production Thinking)

Now think like backend engineer.

---

## Step 1 — Create Database Tables

Create 3 tables in PostgreSQL:

* customers
* orders
* products

Define:

* Primary keys
* Foreign keys
* Proper data types

---

## Step 2 — Insert Cleaned Data

From Pandas → Insert into PostgreSQL.

---

## Step 3 — Write SQL Queries

You must write:

1. Total revenue per city
2. Top 3 customers
3. Monthly revenue trend
4. Category-wise profit
5. Repeat customer percentage

---

## Step 4 — Add Indexes

Create index on:

* customer_id
* order_date
* category

Measure:

* Query time before index
* Query time after index

---

Topics You Learn:

* SELECT with JOIN
* GROUP BY
* COUNT()
* SUM()
* Indexing
* EXPLAIN ANALYZE
* Query optimization basics

---

# 🏁 FINAL DELIVERABLE

You should have:

```
project/
│
├── data/
├── clean_data.py
├── feature_engineering.py
├── db_loader.py
├── analytics.sql
├── requirements.txt
└── Dockerfile (optional)
```

---

# 🧠 What This Actually Builds

This module trains you for:

* RAG ingestion pipelines
* Feature preprocessing
* Embedding data cleaning
* Vector DB indexing
* SQL-based retrieval
* Production AI systems

---

# 🎯 Completion Criteria

You are done when:

✅ You can explain broadcasting
✅ You can write complex groupby without Google
✅ You understand joins deeply
✅ You know when to use index
✅ You can build clean data pipeline

---



In [204]:
import pandas as pd
import numpy as np

order_df=pd.read_csv('/content/orders.csv')


In [205]:
order_df

,order_id,customer_id,product_id,quantity,order_date,price
0,O0001,C001,P012,2,2022-01-20,49.99
1,O0002,C002,P005,1,2022-01-22,299.99
2,O0003,C003,P018,3,2022-02-11,15.50
3,O0004,C004,P021,0,2022-03-02,79.00
4,O0005,C005,P007,2,2022-03-15,NaN
...,...,...,...,...,...,...
246,O0039,C039,P036,2,2023-08-30,NaN
247,O0082,C082,P048,2,2025-05-07,NaN
248,O0001,C001,P012,2,2022-01-20,49.99
249,O0015,C015,P019,2,2022-08-23,199.99


In [206]:
numeric_col=order_df[['quantity','price']]

In [207]:
numeric_col

,quantity,price
0,2,49.99
1,1,299.99
2,3,15.50
3,0,79.00
4,2,NaN
...,...,...
246,2,NaN
247,2,NaN
248,2,49.99
249,2,199.99


In [208]:
order_numeric_array=numeric_col.to_numpy()

In [209]:
order_numeric_array

array([[  2.  ,  49.99],
       [  1.  , 299.99],
       [  3.  ,  15.5 ],
       [  0.  ,  79.  ],
       [  2.  ,    nan],
       [  1.  , 124.  ],
       [  4.  ,  22.  ],
       [  1.  , 399.99],
       [  2.  ,    nan],
       [  3.  ,  18.75],
       [  1.  ,  55.  ],
       [  2.  ,  89.99],
       [  1.  ,    nan],
       [  5.  ,  12.  ],
       [  2.  , 199.99],
       [  1.  , 349.  ],
       [  3.  ,  34.5 ],
       [  2.  ,    nan],
       [  1.  ,  67.  ],
       [  4.  ,  24.99],
       [  2.  , 109.  ],
       [  1.  , 499.99],
       [  3.  ,  41.  ],
       [  2.  ,    nan],
       [  1.  ,  75.  ],
       [  5.  ,  19.99],
       [  2.  , 254.  ],
       [  1.  ,    nan],
       [  3.  ,  33.  ],
       [  2.  , 149.99],
       [  1.  ,  89.  ],
       [  4.  ,  27.5 ],
       [  2.  ,    nan],
       [  1.  , 320.  ],
       [  3.  ,  44.  ],
       [  2.  ,    nan],
       [  1.  , 179.99],
       [  5.  ,  21.  ],
       [  2.  ,    nan],
       [  1.  , 429.  ],


In [210]:
quantity=order_numeric_array[:,0]
quantity


array([ 2.,  1.,  3.,  0.,  2.,  1.,  4.,  1.,  2.,  3.,  1.,  2.,  1.,
        5.,  2.,  1.,  3.,  2.,  1.,  4.,  2.,  1.,  3.,  2.,  1.,  5.,
        2.,  1.,  3.,  2.,  1.,  4.,  2.,  1.,  3.,  2.,  1.,  5.,  2.,
        1.,  3.,  2.,  1.,  4.,  2.,  1.,  3.,  2.,  1.,  5.,  2.,  1.,
        3.,  2., -1.,  1.,  4.,  2.,  1.,  3.,  2.,  1.,  4.,  2.,  1.,
        3.,  2.,  1.,  5.,  2.,  1.,  3.,  2.,  1.,  4.,  2.,  1.,  3.,
        2.,  1.,  0.,  2.,  4.,  1., -2.,  3.,  2.,  1.,  5.,  2.,  1.,
        3.,  2.,  4.,  1.,  2.,  3.,  1.,  2.,  5.,  2.,  1.,  3.,  1.,
        2.,  1.,  4.,  2.,  0.,  1.,  3.,  2.,  1.,  4.,  2.,  1.,  3.,
        2.,  5.,  1.,  2.,  1.,  3.,  2.,  1.,  4.,  2.,  1.,  3.,  2.,
       -1.,  1.,  4.,  2.,  1.,  3.,  2.,  1.,  5.,  2.,  1.,  3.,  2.,
        1.,  4.,  2.,  1.,  3.,  2.,  1.,  4.,  2.,  1.,  3., -1.,  2.,
        1.,  4.,  2.,  1.,  3.,  2.,  1.,  5.,  2.,  1.,  3.,  2.,  1.,
        4.,  2.,  1.,  3.,  2.,  1.,  4.,  2.,  1.,  3.,  2.,  1

In [211]:
price=order_numeric_array[:,1]

In [212]:
price

array([ 49.99, 299.99,  15.5 ,  79.  ,    nan, 124.  ,  22.  , 399.99,
          nan,  18.75,  55.  ,  89.99,    nan,  12.  , 199.99, 349.  ,
        34.5 ,    nan,  67.  ,  24.99, 109.  , 499.99,  41.  ,    nan,
        75.  ,  19.99, 254.  ,    nan,  33.  , 149.99,  89.  ,  27.5 ,
          nan, 320.  ,  44.  ,    nan, 179.99,  21.  ,    nan, 429.  ,
        38.  ,    nan,  95.  ,  16.5 , 269.99,  55.  ,    nan,  72.  ,
       189.  ,  29.99,  49.99,    nan,  15.5 ,  79.  ,  39.  , 124.  ,
          nan, 399.99,  85.  ,    nan,  55.  ,  89.99,    nan,  12.  ,
       199.99, 349.  ,    nan,  67.  ,  24.99,    nan, 109.  , 499.99,
          nan,  75.  ,  19.99, 254.  ,    nan,  33.  , 149.99,  89.  ,
        27.5 ,    nan, 320.  ,  44.  ,  59.99,    nan,  21.  , 179.99,
       429.  ,    nan,  38.  ,  95.  ,    nan, 269.99,  55.  ,    nan,
        72.  , 189.  ,  29.99,  49.99,    nan, 349.  ,  41.  ,  55.  ,
        38.  , 199.99,    nan, 109.  ,  99.99,  33.  ,  24.99,    nan,
      

In [213]:
revenue_per_order=quantity*np.nan_to_num(price,nan=0.0)

In [214]:
revenue_per_order

array([  99.98,  299.99,   46.5 ,    0.  ,    0.  ,  124.  ,   88.  ,
        399.99,    0.  ,   56.25,   55.  ,  179.98,    0.  ,   60.  ,
        399.98,  349.  ,  103.5 ,    0.  ,   67.  ,   99.96,  218.  ,
        499.99,  123.  ,    0.  ,   75.  ,   99.95,  508.  ,    0.  ,
         99.  ,  299.98,   89.  ,  110.  ,    0.  ,  320.  ,  132.  ,
          0.  ,  179.99,  105.  ,    0.  ,  429.  ,  114.  ,    0.  ,
         95.  ,   66.  ,  539.98,   55.  ,    0.  ,  144.  ,  189.  ,
        149.95,   99.98,    0.  ,   46.5 ,  158.  ,  -39.  ,  124.  ,
          0.  ,  799.98,   85.  ,    0.  ,  110.  ,   89.99,    0.  ,
         24.  ,  199.99, 1047.  ,    0.  ,   67.  ,  124.95,    0.  ,
        109.  , 1499.97,    0.  ,   75.  ,   79.96,  508.  ,    0.  ,
         99.  ,  299.98,   89.  ,    0.  ,    0.  , 1280.  ,   44.  ,
       -119.98,    0.  ,   42.  ,  179.99, 2145.  ,    0.  ,   38.  ,
        285.  ,    0.  , 1079.96,   55.  ,    0.  ,  216.  ,  189.  ,
         59.98,  249

In [215]:
mean_price = np.nanmean(price)

In [216]:
mean_price

np.float64(122.17524590163934)

In [217]:
median_price=np.nanmedian(price)

In [218]:
median_price

np.float64(75.0)

In [219]:
standard_deviation_price=np.nanstd(price)

In [220]:
standard_deviation_price

np.float64(126.70709616858501)

In [221]:
mask=normalized_price>0

In [222]:
mask

array([False,  True, False, False, False,  True, False,  True, False,
       False, False, False, False, False,  True,  True, False, False,
       False, False, False,  True, False, False, False, False,  True,
       False, False,  True, False, False, False,  True, False, False,
        True, False, False,  True, False, False, False, False,  True,
       False, False, False,  True, False, False, False, False, False,
       False,  True, False,  True, False, False, False, False, False,
       False,  True,  True, False, False, False, False, False,  True,
       False, False, False,  True, False, False,  True, False, False,
       False,  True, False, False, False, False,  True,  True, False,
       False, False, False,  True, False, False, False,  True, False,
       False, False,  True, False, False, False,  True, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False,  True,  True,  True, False, False,  True, False,
       False, False,

In [223]:
masked_price=normalized_price[mask]


In [224]:
masked_price

array([1.40335277, 0.01440136, 2.19257455, 0.61413099, 1.79015036,
       2.98179633, 1.04038967, 0.2195201 , 1.56127605, 0.45628663,
       2.42152779, 1.16658623, 0.52739551, 0.01440136, 2.19257455,
       0.61413099, 1.79015036, 2.98179633, 1.04038967, 0.2195201 ,
       1.56127605, 0.45628663, 2.42152779, 1.16658623, 0.52739551,
       1.79015036, 0.61413099, 2.19257455, 0.01440136, 2.98179633,
       0.45628663, 0.2195201 , 1.40335277, 2.42152779, 1.16658623,
       0.52739551, 2.19257455, 0.45628663, 1.56127605, 0.2195201 ,
       1.40335277, 2.98179633, 0.61413099, 1.04038967, 0.45628663,
       1.79015036, 2.42152779, 1.16658623, 2.19257455, 0.01440136,
       0.2195201 , 2.42152779, 0.61413099, 0.45628663, 2.98179633,
       0.61413099])

In [225]:

normalized_price = (price - mean_price) / standard_deviation_price


In [226]:
normalized_price

array([-0.56970168,  1.40335277, -0.84190427, -0.34074844,         nan,
        0.01440136, -0.79060486,  2.19257455,         nan, -0.81625457,
       -0.53016167, -0.25401297,         nan, -0.86952704,  0.61413099,
        1.79015036, -0.69195214,         nan, -0.43545506, -0.76700713,
       -0.10398191,  2.98179633, -0.64065272,         nan, -0.37231732,
       -0.80646822,  1.04038967,         nan, -0.70379046,  0.2195201 ,
       -0.26182627, -0.74719766,         nan,  1.56127605, -0.61697607,
               nan,  0.45628663, -0.79849708,         nan,  2.42152779,
       -0.66432937,         nan, -0.21447296, -0.83401206,  1.16658623,
       -0.53016167,         nan, -0.39599397,  0.52739551, -0.72754604,
       -0.56970168,         nan, -0.84190427, -0.34074844, -0.65643716,
        0.01440136,         nan,  2.19257455, -0.29339514,         nan,
       -0.53016167, -0.25401297,         nan, -0.86952704,  0.61413099,
        1.79015036,         nan, -0.43545506, -0.76700713,      

In [227]:
valid_mask=~np.isnan(price) & ~np.isnan(quantity)

In [228]:
clean_qty=quantity[valid_mask]
clean_price=price[valid_mask]



In [229]:
clean_price

array([ 49.99, 299.99,  15.5 ,  79.  , 124.  ,  22.  , 399.99,  18.75,
        55.  ,  89.99,  12.  , 199.99, 349.  ,  34.5 ,  67.  ,  24.99,
       109.  , 499.99,  41.  ,  75.  ,  19.99, 254.  ,  33.  , 149.99,
        89.  ,  27.5 , 320.  ,  44.  , 179.99,  21.  , 429.  ,  38.  ,
        95.  ,  16.5 , 269.99,  55.  ,  72.  , 189.  ,  29.99,  49.99,
        15.5 ,  79.  ,  39.  , 124.  , 399.99,  85.  ,  55.  ,  89.99,
        12.  , 199.99, 349.  ,  67.  ,  24.99, 109.  , 499.99,  75.  ,
        19.99, 254.  ,  33.  , 149.99,  89.  ,  27.5 , 320.  ,  44.  ,
        59.99,  21.  , 179.99, 429.  ,  38.  ,  95.  , 269.99,  55.  ,
        72.  , 189.  ,  29.99,  49.99, 349.  ,  41.  ,  55.  ,  38.  ,
       199.99, 109.  ,  99.99,  33.  ,  24.99, 399.99,  67.  ,  79.  ,
        75.  ,  85.  , 124.  , 499.99, 179.99,  89.  , 149.99,  12.  ,
        38.  , 299.99, 429.  ,  29.99,  16.5 ,  55.  ,  22.  ,  24.99,
        89.99,  44.  , 269.99,  19.99,  18.75, 189.  ,  72.  ,  34.5 ,
      

In [230]:
clean_qty

array([ 2.,  1.,  3.,  0.,  1.,  4.,  1.,  3.,  1.,  2.,  5.,  2.,  1.,
        3.,  1.,  4.,  2.,  1.,  3.,  1.,  5.,  2.,  3.,  2.,  1.,  4.,
        1.,  3.,  1.,  5.,  1.,  3.,  1.,  4.,  2.,  1.,  2.,  1.,  5.,
        2.,  3.,  2., -1.,  1.,  2.,  1.,  2.,  1.,  2.,  1.,  3.,  1.,
        5.,  1.,  3.,  1.,  4.,  2.,  3.,  2.,  1.,  0.,  4.,  1., -2.,
        2.,  1.,  5.,  1.,  3.,  4.,  1.,  3.,  1.,  2.,  5.,  1.,  3.,
        1.,  2.,  1.,  2.,  0.,  1.,  3.,  1.,  4.,  1.,  3.,  5.,  1.,
        2.,  1.,  2.,  1.,  4.,  1.,  3.,  2., -1.,  4.,  2.,  1.,  2.,
        1.,  2.,  1.,  2.,  1.,  4.,  1.,  3.,  2.,  4.,  2.,  1.,  3.,
       -1.,  1.,  4.,  2.,  1.,  2.,  1.,  5.,  1.,  3.,  2.,  4.,  2.,
        1.,  2.,  1.,  2.,  1.,  3.,  1.,  0.,  3.,  1.,  2.,  1.,  2.,
        1., -2.,  2.,  1.,  4.,  1.,  3.,  2.,  4.,  2.,  3.,  2.,  1.,
        2.,  1.,  3.,  1.,  5.,  1.,  3.,  1.,  4.,  1.,  3.,  2.,  1.,
        2.,  1.,  1.,  3.,  2.,  4.,  2.,  1.,  0., -1., -2.,  2

In [231]:
correlation_matrix=np.corrcoef(clean_qty,clean_price)

In [232]:
correlation_matrix

array([[ 1.        , -0.09649813],
       [-0.09649813,  1.        ]])

In [233]:

correlation_matrix[:1]

array([[ 1.        , -0.09649813]])

In [234]:
print(order_df.head())

  order_id customer_id product_id  quantity  order_date   price
0    O0001        C001       P012         2  2022-01-20   49.99
1    O0002        C002       P005         1  2022-01-22  299.99
2    O0003        C003       P018         3  2022-02-11   15.50
3    O0004        C004       P021         0  2022-03-02   79.00
4    O0005        C005       P007         2  2022-03-15     NaN


In [235]:
order_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 251 entries, 0 to 250
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   order_id     251 non-null    object 
 1   customer_id  251 non-null    object 
 2   product_id   251 non-null    object 
 3   quantity     251 non-null    int64  
 4   order_date   251 non-null    object 
 5   price        183 non-null    float64
dtypes: float64(1), int64(1), object(4)
memory usage: 11.9+ KB


In [236]:
order_df.describe()

,quantity,price
count,251.000000,183.000000
mean,2.055777,122.175246
std,1.313346,127.054716
min,-2.000000,12.000000
25%,1.000000,34.500000
50%,2.000000,75.000000
75%,3.000000,179.990000
max,5.000000,499.990000


In [237]:
order_df.isnull().sum()

,0
order_id,0
customer_id,0
product_id,0
quantity,0
order_date,0
price,68


In [238]:
order_df.duplicated().sum()

np.int64(12)

In [239]:

customers_df = pd.read_csv('/content/customers.csv')
products_df = pd.read_csv('/content/products.csv')



In [240]:
order_df.drop_duplicates()

,order_id,customer_id,product_id,quantity,order_date,price
0,O0001,C001,P012,2,2022-01-20,49.99
1,O0002,C002,P005,1,2022-01-22,299.99
2,O0003,C003,P018,3,2022-02-11,15.50
3,O0004,C004,P021,0,2022-03-02,79.00
4,O0005,C005,P007,2,2022-03-15,NaN
...,...,...,...,...,...,...
234,O0235,C080,P041,1,2025-04-18,85.00
235,O0236,C090,P020,3,2025-09-04,NaN
236,O0237,C004,P021,0,2022-03-02,79.00
237,O0238,C055,P007,-1,2024-04-21,39.00


In [241]:
order_df[order_df['quantity'] >= 0]

,order_id,customer_id,product_id,quantity,order_date,price
0,O0001,C001,P012,2,2022-01-20,49.99
1,O0002,C002,P005,1,2022-01-22,299.99
2,O0003,C003,P018,3,2022-02-11,15.50
3,O0004,C004,P021,0,2022-03-02,79.00
4,O0005,C005,P007,2,2022-03-15,NaN
...,...,...,...,...,...,...
246,O0039,C039,P036,2,2023-08-30,NaN
247,O0082,C082,P048,2,2025-05-07,NaN
248,O0001,C001,P012,2,2022-01-20,49.99
249,O0015,C015,P019,2,2022-08-23,199.99


In [242]:

order_df['price'].fillna(median_price, inplace=True)



/tmp/ipython-input-1076281204.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  order_df['price'].fillna(median_price, inplace=True)


### Cleaning `customers_df`

In [243]:
customers_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 216 entries, 0 to 215
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   customer_id  216 non-null    object 
 1   name         216 non-null    object 
 2   age          186 non-null    float64
 3   city         213 non-null    object 
 4   signup_date  216 non-null    object 
dtypes: float64(1), object(4)
memory usage: 8.6+ KB


In [244]:
customers_df.describe()

,age
count,186.000000
mean,36.516129
std,8.884378
min,21.000000
25%,29.000000
50%,36.000000
75%,43.000000
max,56.000000


In [245]:
customers_df


,customer_id,name,age,city,signup_date
0,C001,Alice Johnson,34.0,New York,2022-01-15
1,C002,Bob Smith,28.0,Los Angeles,2022-02-03
2,C003,Carol White,NaN,Chicago,2022-02-10
3,C004,David Brown,45.0,Houston,2022-03-01
4,C005,Eva Green,31.0,Phoenix,2022-03-14
...,...,...,...,...,...
211,C007,Grace Kim,39.0,San Antonio,2022-04-18
212,C019,Steve Robinson,NaN,Nashville,2022-10-19
213,C045,Ryan Collins,42.0,Tulsa,2023-11-30
214,C082,Alice Brown,35.0,Lubbock,2025-04-09


In [246]:
customers_df.isnull().sum()

,0
customer_id,0
name,0
age,30
city,3
signup_date,0


In [247]:
customers_df['age'].fillna(customers_df['age'].median(), inplace=True)

/tmp/ipython-input-358517450.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  customers_df['age'].fillna(customers_df['age'].median(), inplace=True)


### Cleaning `products_df`

In [248]:
products_df['category'].str.lower().str.strip()

,category
0,electronics
1,electronics
2,electronics
3,electronics
4,electronics
5,electronics
6,electronics
7,accessories
8,accessories
9,accessories


In [253]:
display(order_df.head())
display(customers_df.head())
display(products_df.head())


,order_id,customer_id,product_id,quantity,order_date,price
0,O0001,C001,P012,2,2022-01-20,49.99
1,O0002,C002,P005,1,2022-01-22,299.99
2,O0003,C003,P018,3,2022-02-11,15.50
3,O0004,C004,P021,0,2022-03-02,79.00
4,O0005,C005,P007,2,2022-03-15,75.00


,customer_id,name,age,city,signup_date
0,C001,Alice Johnson,34.0,New York,2022-01-15
1,C002,Bob Smith,28.0,Los Angeles,2022-02-03
2,C003,Carol White,36.0,Chicago,2022-02-10
3,C004,David Brown,45.0,Houston,2022-03-01
4,C005,Eva Green,31.0,Phoenix,2022-03-14


,product_id,product_name,category,cost_price
0,P001,Wireless Mouse,Electronics,12.5
1,P002,USB-C Hub,electronics,18.0
2,P003,Mechanical Keyboard,Electronics,95.0
3,P004,27-inch Monitor,ELECTRONICS,320.0
4,P005,Noise-Cancelling Headphones,Electronics,145.0


In [255]:
order_df.info()
customers_df.info()
products_df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 251 entries, 0 to 250
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   order_id     251 non-null    object 
 1   customer_id  251 non-null    object 
 2   product_id   251 non-null    object 
 3   quantity     251 non-null    int64  
 4   order_date   251 non-null    object 
 5   price        251 non-null    float64
dtypes: float64(1), int64(1), object(4)
memory usage: 11.9+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 216 entries, 0 to 215
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   customer_id  216 non-null    object 
 1   name         216 non-null    object 
 2   age          216 non-null    float64
 3   city         213 non-null    object 
 4   signup_date  216 non-null    object 
dtypes: float64(1), object(4)
memory usage: 8.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeInde

In [256]:
bins = [0, 18, 25, 40, 60, 100]
labels = ['<18', '18-25', '26-40', '41-60', '60+']
customers_df['age_group'] = pd.cut(customers_df['age'], bins=bins, labels=labels, right=False)

display(customers_df.head())

,customer_id,name,age,city,signup_date,age_group
0,C001,Alice Johnson,34.0,New York,2022-01-15,26-40
1,C002,Bob Smith,28.0,Los Angeles,2022-02-03,26-40
2,C003,Carol White,36.0,Chicago,2022-02-10,26-40
3,C004,David Brown,45.0,Houston,2022-03-01,41-60
4,C005,Eva Green,31.0,Phoenix,2022-03-14,26-40


In [259]:

order_df['order_date'] = pd.to_datetime(order_df['order_date'])
order_df['order_month'] = order_df['order_date'].dt.to_period('M')


display(order_df.head())

,order_id,customer_id,product_id,quantity,order_date,price,order_month,is_repeat_customer
0,O0001,C001,P012,2,2022-01-20,49.99,2022-01,True
1,O0002,C002,P005,1,2022-01-22,299.99,2022-01,True
2,O0003,C003,P018,3,2022-02-11,15.50,2022-02,False
3,O0004,C004,P021,0,2022-03-02,79.00,2022-03,True
4,O0005,C005,P007,2,2022-03-15,75.00,2022-03,False


In [258]:

customer_order_counts = order_df['customer_id'].value_counts()
repeat_customers = customer_order_counts[customer_order_counts > 1].index
order_df['is_repeat_customer'] = order_df['customer_id'].isin(repeat_customers)
display(order_df.head())
display(order_df[order_df['is_repeat_customer'] == True].head())

,order_id,customer_id,product_id,quantity,order_date,price,order_month,is_repeat_customer
0,O0001,C001,P012,2,2022-01-20,49.99,2022-01,True
1,O0002,C002,P005,1,2022-01-22,299.99,2022-01,True
2,O0003,C003,P018,3,2022-02-11,15.50,2022-02,False
3,O0004,C004,P021,0,2022-03-02,79.00,2022-03,True
4,O0005,C005,P007,2,2022-03-15,75.00,2022-03,False


,order_id,customer_id,product_id,quantity,order_date,price,order_month,is_repeat_customer
0,O0001,C001,P012,2,2022-01-20,49.99,2022-01,True
1,O0002,C002,P005,1,2022-01-22,299.99,2022-01,True
3,O0004,C004,P021,0,2022-03-02,79.00,2022-03,True
8,O0009,C009,P041,2,2022-05-21,75.00,2022-05,True
9,O0010,C010,P002,3,2022-06-02,18.75,2022-06,True


In [260]:
order_df['total_amount'] = order_df['quantity'] * order_df['price']

In [261]:
display(order_df.head())

,order_id,customer_id,product_id,quantity,order_date,price,order_month,is_repeat_customer,total_amount
0,O0001,C001,P012,2,2022-01-20,49.99,2022-01,True,99.98
1,O0002,C002,P005,1,2022-01-22,299.99,2022-01,True,299.99
2,O0003,C003,P018,3,2022-02-11,15.50,2022-02,False,46.50
3,O0004,C004,P021,0,2022-03-02,79.00,2022-03,True,0.00
4,O0005,C005,P007,2,2022-03-15,75.00,2022-03,False,150.00


### Step 4 — Groupby Analytics

In [265]:
merged_df = pd.merge(order_df, customers_df, on='customer_id', how='left')
merged_df_1=pd.merge(merged_df,products_df,on='product_id',how='left')
display(merged_df_1.head())

,order_id,customer_id,product_id,quantity,order_date,price,order_month,is_repeat_customer,total_amount,name,age,city,signup_date,age_group,product_name,category,cost_price
0,O0001,C001,P012,2,2022-01-20,49.99,2022-01,True,99.98,Alice Johnson,34.0,New York,2022-01-15,26-40,Ergonomic Chair Cushion,Furniture,19.0
1,O0001,C001,P012,2,2022-01-20,49.99,2022-01,True,99.98,Alice Johnson,34.0,New York,2022-01-15,26-40,Ergonomic Chair Cushion,Furniture,19.0
2,O0002,C002,P005,1,2022-01-22,299.99,2022-01,True,299.99,Bob Smith,28.0,Los Angeles,2022-02-03,26-40,Noise-Cancelling Headphones,Electronics,145.0
3,O0003,C003,P018,3,2022-02-11,15.50,2022-02,False,46.50,Carol White,36.0,Chicago,2022-02-10,26-40,Sticky Notes Pack,Office Supplies,2.5
4,O0004,C004,P021,0,2022-03-02,79.00,2022-03,True,0.00,David Brown,45.0,Houston,2022-03-01,41-60,A4 Notebook,Office Supplies,6.0


In [266]:
revenue_per_city = merged_df_1.groupby('city')['total_amount'].sum().sort_values(ascending=False)
revenue_per_city

,total_amount
city,
Irvine,2145.00
Eugene,1934.00
Jersey City,1499.97
Winston-Salem,1280.00
Fort Collins,1199.97
...,...
Durham,0.00
Houston,0.00
Montgomery,-29.99


In [269]:
monthly_revenue_trend = merged_df_1.groupby('order_month')['total_amount'].sum().reset_index()
monthly_revenue_trend['order_month'] = monthly_revenue_trend['order_month'].astype(str) # Convert Period to string for better display
display(monthly_revenue_trend)


,order_month,total_amount
0,2022-01,699.91
1,2022-02,695.50
2,2022-03,150.00
3,2022-04,497.99
4,2022-05,887.99
5,2022-06,2224.22
6,2022-07,365.99
7,2022-08,991.96
8,2022-09,782.48
9,2022-10,898.99
